sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: xVhfxQnZz70Z/YoA3Ji6kEa9B9qN/dYINfqVHfGuOZDrZ4JNYEhLWIYn+4rKBzKwHuygrmRznugUu1bgqaRh6mTubqojjUoS1WvQsZfQNVRsnnHakGIYLnxQqjEv94+ONb5uAQ0PeU83gFm04/DOZWbB2RxxXEg7FMuyviv/jOMWiu3Mb60u5MKsJ/LQUQ7i6fDNWuKYX4jyWKxgy8zUhbwfo64zTljXZx86lk/+X6LBLkGojBD9Vl1u2Wp2e3RW3b9xCt/nUWGoKcNsQy4Nj8RhSJw7+HI8MAqC5VVt98NT3gJ4nfQot3qphop780K6M5mmVwlwj2oyd2+RBLrJXvhk8gibUb2xCPwymDEbgKJKpwJDo4TX96oAu8KNWF9vHiqvXs0lzVcVbZbPi/9cvMP2i0kVqSPGrWpoM/DXaxrlu465FpuZv1MiwPK9AGoID2jKgyH3tx0m7YFGEDjFh+jdE9ZYn4+f4HXY1gEBPDlwWfyrlzG72zR5uBiFiy+PMO+MF/Jyx8Ld+1e6YpuXGO16RycffRPkT6HUr+zM2plJ0RHniEYbNiCgGU6xcalq5ZdtSsBYi1vVux/2t00A9G+Lk96QlBrpSt8AnpigVnOGA/KDC0sPkZBupGgOJGv0qN66e19S5c+VV2RHNlI1inesfkmw/uYAlsrHSIo11nI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Haunted-Bookshop_172
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy